sudo: false
dist: trusty
language: node_js
node_js:
- 8
- 6
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm run check
- npm run build
- npm run build:lib
branches:
  only:
  - master
